import { StyleSheet } from "react-native";
import { COLORS } from "@/constants/Colors";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    content: {
        padding: 20,
        paddingBottom: 0,
    },
    header: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
        paddingHorizontal: 0,
        paddingVertical: 12,
    },
    headerLeft: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
    },
    headerLogo: {
        width: 75,
        height: 75,
    },
    welcomeContainer: {
        flex: 1,
    },
    welcomeText: {
        fontSize: 14,
        color: COLORS.textLight,
        marginBottom: 2,
    },
    usernameText: {
        fontSize: 16,
        fontWeight: "600",
        color: COLORS.text,
    },
    headerRight: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    headerTitle: {
        fontSize: 28,
        fontWeight: "bold",
        color: COLORS.text,
    },
    addButton: {
        backgroundColor: COLORS.primary,
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 24,
        flexDirection: "row",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    addButtonText: {
        color: COLORS.white,
        fontWeight: "600",
        marginLeft: 4,
    },
    logoutButton: {
        padding: 10,
        borderRadius: 20,
        backgroundColor: COLORS.card,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    themeButton: {
        padding: 10,
        borderRadius: 20,
        backgroundColor: COLORS.card,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    balanceCard: {
        backgroundColor: COLORS.card,
        borderRadius: 20,
        padding: 20,
        marginBottom: 20,
        shadowColor: COLORS.shadow,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
    balanceTitle: {
        fontSize: 16,
        color: COLORS.textLight,
        marginBottom: 8,
    },
    balanceAmount: {
        fontSize: 32,
        fontWeight: "bold",
        color: COLORS.text,
        marginBottom: 20,
    },
    balanceStats: {
        flexDirection: "row",
        justifyContent: "space-between",
    },
    balanceStatItem: {
        flex: 1,
        alignItems: "center",
    },
    statDivider: {
        borderRightWidth: 1,
        borderColor: COLORS.border,
    },
    balanceStatLabel: {
        fontSize: 14,
        color: COLORS.textLight,
        marginBottom: 4,
    },
    balanceStatAmount: {
        fontSize: 18,
        fontWeight: "600",
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "600",
        color: COLORS.text,
        marginBottom: 15,
    },
    transactionCard: {
        backgroundColor: COLORS.card,
        borderRadius: 12,
        marginBottom: 10,
        flexDirection: "row",
        alignItems: "center",
        shadowColor: COLORS.shadow,
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    transactionContent: {
        flex: 1,
        flexDirection: "row",
        padding: 15,
        alignItems: "center",
    },
    categoryIconContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "#F5F5F5",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 12,
    },
    transactionLeft: {
        flex: 1,
    },
    transactionTitle: {
        fontSize: 16,
        fontWeight: "500",
        color: COLORS.text,
        marginBottom: 4,
    },
    transactionCategory: {
        fontSize: 14,
        color: COLORS.textLight,
    },
    transactionRight: {
        alignItems: "flex-end",
    },
    transactionAmount: {
        fontSize: 16,
        fontWeight: "600",
        marginBottom: 4,
    },
    transactionDate: {
        fontSize: 12,
        color: COLORS.textLight,
    },
    deleteButton: {
        padding: 15,
        borderLeftWidth: 1,
        borderLeftColor: COLORS.border,
    },
    transactionsContainer: {
        marginBottom: 20,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: COLORS.background,
    },
    emptyState: {
        backgroundColor: COLORS.card,
        borderRadius: 16,
        padding: 30,
        alignItems: "center",
        justifyContent: "center",
        marginTop: 10,
        shadowColor: COLORS.shadow,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    emptyStateIcon: {
        marginBottom: 16,
    },
    emptyStateTitle: {
        fontSize: 18,
        fontWeight: "600",
        color: COLORS.text,
        marginBottom: 8,
    },
    emptyStateText: {
        color: COLORS.textLight,
        fontSize: 14,
        textAlign: "center",
        marginBottom: 20,
        lineHeight: 20,
    },
    emptyStateButton: {
        backgroundColor: COLORS.primary,
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 20,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
    },
    emptyStateButtonText: {
        color: COLORS.white,
        fontWeight: "600",
        marginLeft: 6,
    },
    transactionsHeaderContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 10,
        paddingBottom: 5,
    },
    transactionsList: {
        flex: 1,
        marginHorizontal: 20,
    },
    transactionsListContent: {
        paddingBottom: 20,
    },
    calendarWrap: {
        marginTop: 10,
        marginBottom: 20,
        borderRadius: 14,
        overflow: 'hidden',
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.07,
        shadowRadius: 6,
        elevation: 2,
    },
    row: {
        flexDirection: 'row',
    },
    headerCell: {
        width: 85,
        minWidth: 85,
        maxWidth: 85,
        backgroundColor: '#ffe9a7',
        paddingVertical: 10,
        borderWidth: 1,
        borderColor: '#f3e2a9',
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerText: {
        fontWeight: 'bold',
        fontSize: 16,
        color: '#b8860b',
        letterSpacing: 1,
    },
    cell: {
        width: 85,
        minWidth: 85,
        maxWidth: 85,
        minHeight: 75,
        borderWidth: 1,
        borderColor: '#f3e2a9',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fff',
        padding: 4,
        position: 'relative',
        borderRadius: 0,
        margin: 0,
    },
    savedCell: {
        backgroundColor: '#d0f5e8',
        borderColor: '#2ecc71',
    },
    dateText: {
        fontSize: 15,
        color: '#b8860b',
        fontWeight: '600',
        marginBottom: 2,
    },
    amountText: {
        fontSize: 16,
        color: '#6d4c00',
        fontWeight: 'bold',
        marginTop: 2,
    },
    checkMark: {
        position: 'absolute',
        right: 6,
        top: 4,
        color: '#2ecc71',
        fontWeight: 'bold',
        fontSize: 20,
    },
});